server:
  port: 7777
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/IjodkorlarDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-request-size: 999999MB
      max-file-size: 999999MB

telegram_bot_username: creative_you_bot
telegram_bot_botToken: 5223329405:AAFgbKW5IYYaFCgjMoHkCmPJ2-ReCEtnfEM

